Move sclockadj build into postinst, remove obsolete adduser call

diff --git a/debian/sdwdate.postinst b/debian/sdwdate.postinst
--- a/debian/sdwdate.postinst
+++ b/debian/sdwdate.postinst
@@ -56,10 +56,24 @@ case "$1" in
        ## already successfully established a circuit before fetching time.
        adduser sdwdate debian-tor
 
-       ## required for anondate which uses journalctl
-       ## Not possible here, because
-       ## group systemd-journal might not exist yet during the build process.
-       #adduser sdwdate systemd-journal
+       ## Build sclockadj program.
+       if ! pushd /usr/src/sdwdate >dev/null ; then
+         printf '%s\n' "Cannot change to '/usr/src/sdwdate'!" >&2
+         exit 1
+       fi
+       if ! make ; then
+         printf '%s\n' "Error building sclockadj!" >&2
+         exit 1
+       fi
+       if ! rm -f -- /usr/libexec/sdwdate/sclockadj ; then
+         printf '%s\n' "Cannot remove old sclockadj!" >&2
+         exit 1
+       fi
+       if ! mv sclockadj /usr/libexec/sdwdate/sclockadj ; then
+         printf '%s\n' "Cannot move sclockadj to '/usr/libexec/sdwdate'!" >&2
+         exit 1
+       fi
+       popd >/dev/null
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
