safer sdwdate.log permissions

diff --git a/usr/lib/sdwdate/suspend-post b/usr/lib/sdwdate/suspend-post
--- a/usr/lib/sdwdate/suspend-post
+++ b/usr/lib/sdwdate/suspend-post
@@ -16,14 +16,14 @@ if [ -f /var/run/qubes/this-is-templatevm ]; then
 fi
 
 if [ ! "$(id -u)" = "0" ]; then
-   echo "$(date_cmd) - $0 - ERROR - Must run as root!" >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - ERROR - Must run as root!" | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
    exit 2
 fi
 
 if command -v "qubesdb-read" >/dev/null 2>&1 ; then
    true
 else
-   echo "$(date_cmd) - $0 - INFO - Clock fix after resume not implemented in Non-Qubes-Whonix. See: https://www.whonix.org/wiki/Troubleshooting#Clock_Fix" >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - Clock fix after resume not implemented in Non-Qubes-Whonix. See: https://www.whonix.org/wiki/Troubleshooting#Clock_Fix" | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
    exit 3
 fi
 
@@ -33,15 +33,15 @@ chown --recursive sdwdate:sdwdate /var/run/sdwdate
 
 tor_restart_maybe() {
    if test -f /var/run/sdwdate/tor_was_running.status ; then
-      echo "$(date_cmd) - $0 - INFO - Deleting /var/run/sdwdate/tor_was_running.status..." >> /var/log/sdwdate.log
+      echo "$(date_cmd) - $0 - INFO - Deleting /var/run/sdwdate/tor_was_running.status..." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
       rm -f /var/run/sdwdate/sdwdate_was_running.status
-      echo "$(date_cmd) - $0 - INFO - Done, deleted /var/run/sdwdate/tor_was_running.status." >> /var/log/sdwdate.log
+      echo "$(date_cmd) - $0 - INFO - Done, deleted /var/run/sdwdate/tor_was_running.status." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
 
-      echo "$(date_cmd) - $0 - INFO - Restarting Tor..." >> /var/log/sdwdate.log
+      echo "$(date_cmd) - $0 - INFO - Restarting Tor..." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
       systemctl --no-pager restart tor@default
-      echo "$(date_cmd) - $0 - INFO - Done, restarted Tor." >> /var/log/sdwdate.log
+      echo "$(date_cmd) - $0 - INFO - Done, restarted Tor." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
    else
-      echo "$(date_cmd) - $0 - INFO - File /var/run/sdwdate/tor_was_running.status did not exist, meaning we previously did not stop Tor so not starting it now." >> /var/log/sdwdate.log
+      echo "$(date_cmd) - $0 - INFO - File /var/run/sdwdate/tor_was_running.status did not exist, meaning we previously did not stop Tor so not starting it now." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
    fi
 }
 
@@ -62,27 +62,27 @@ tor_restart_maybe() {
 
 ## Do not interfere with the clock if the service was stopped.
 if test -f /var/run/sdwdate/sdwdate_was_running.status ; then
-   echo "$(date_cmd) - $0 - INFO - Deleting /var/run/sdwdate/sdwdate_was_running.status..." >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - Deleting /var/run/sdwdate/sdwdate_was_running.status..." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
    rm -f /var/run/sdwdate/sdwdate_was_running.status
-   echo "$(date_cmd) - $0 - INFO - Done, deleted /var/run/sdwdate/sdwdate_was_running.status." >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - Done, deleted /var/run/sdwdate/sdwdate_was_running.status." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
 
    randomized_unix_time="$(timeout --kill-after="5" "5" /usr/lib/qubes/qrexec-client-vm dom0 qubes.GetRandomizedTime)"
 
-   echo "$(date_cmd) - $0 - INFO - date before roughly fixing it: $(date -u)" >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - date before roughly fixing it: $(date -u)" | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
 
    date --set "@$randomized_unix_time" >/dev/null
 
-   echo "$(date_cmd) - $0 - INFO - date after roughly fixing it : $(date -u)" >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - date after roughly fixing it : $(date -u)" | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
 
    tor_restart_maybe
 
-   echo "$(date_cmd) - $0 - INFO - Running /usr/lib/sdwdate/restart_fresh..." >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - Running /usr/lib/sdwdate/restart_fresh..." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
    /usr/lib/sdwdate/restart_fresh
-   echo "$(date_cmd) - $0 - INFO - Done, with /usr/lib/sdwdate/restart_fresh." >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - Done, with /usr/lib/sdwdate/restart_fresh." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
 
-   echo "$(date_cmd) - $0 - INFO - Restarting sdwdate..." >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - Restarting sdwdate..." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
    systemctl --no-pager restart sdwdate
-   echo "$(date_cmd) - $0 - INFO - Done, restarted sdwdate." >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - Done, restarted sdwdate." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
 
    ## Whonix firewall full mode
    ##
@@ -95,7 +95,7 @@ if test -f /var/run/sdwdate/sdwdate_was_running.status ; then
 
    exit 0
 else
-   echo "$(date_cmd) - $0 - INFO - File /var/run/sdwdate/sdwdate_was_running.status did not exist, meaning we previously did not stop sdwdate so not starting it now." >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - File /var/run/sdwdate/sdwdate_was_running.status did not exist, meaning we previously did not stop sdwdate so not starting it now." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
 fi
 
 ## Make sure Tor is restarted even if sdwdate was not running during suspend-pre.
diff --git a/usr/lib/sdwdate/suspend-pre b/usr/lib/sdwdate/suspend-pre
--- a/usr/lib/sdwdate/suspend-pre
+++ b/usr/lib/sdwdate/suspend-pre
@@ -16,14 +16,14 @@ if [ -f /var/run/qubes/this-is-templatevm ]; then
 fi
 
 if [ ! "$(id -u)" = "0" ]; then
-   echo "$(date_cmd) - $0 - ERROR - Must run as root!" >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - ERROR - Must run as root!" | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
    exit 2
 fi
 
 if command -v "qubesdb-read" >/dev/null 2>&1 ; then
    true
 else
-   echo "$(date_cmd) - $0 - INFO - Clock fix after resume not implemented in Non-Qubes-Whonix. See: https://www.whonix.org/wiki/Troubleshooting#Clock_Fix" >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - Clock fix after resume not implemented in Non-Qubes-Whonix. See: https://www.whonix.org/wiki/Troubleshooting#Clock_Fix" | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
    exit 3
 fi
 
@@ -36,42 +36,42 @@ chown --recursive sdwdate:sdwdate /var/run/sdwdate
 ## unnecessary fetching errors to /var/log/sdwdate.log.
 
 if systemctl --no-pager status sdwdate >/dev/null ; then
-   echo "$(date_cmd) - $0 - INFO - Creating /var/run/sdwdate/sdwdate_was_running.status..." >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - Creating /var/run/sdwdate/sdwdate_was_running.status..." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
    touch /var/run/sdwdate/sdwdate_was_running.status
-   echo "$(date_cmd) - $0 - INFO - Done, created /var/run/sdwdate/sdwdate_was_running.status." >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - Done, created /var/run/sdwdate/sdwdate_was_running.status." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
 
-   echo "$(date_cmd) - $0 - INFO - Stopping sdwdate..." >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - Stopping sdwdate..." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
    systemctl --no-pager stop sdwdate
-   echo "$(date_cmd) - $0 - INFO - Done, stopped sdwdate." >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - Done, stopped sdwdate." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
 
-   echo "$(date_cmd) - $0 - INFO - Deleting /var/run/sdwdate/first_success..." >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - Deleting /var/run/sdwdate/first_success..." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
    rm -f /var/run/sdwdate/first_success
-   echo "$(date_cmd) - $0 - INFO - Done, deleted /var/run/sdwdate/first_success." >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - Done, deleted /var/run/sdwdate/first_success." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
 
-   echo "$(date_cmd) - $0 - INFO - Deleting /var/run/sdwdate/success..." >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - Deleting /var/run/sdwdate/success..." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
    rm -f /var/run/sdwdate/success
-   echo "$(date_cmd) - $0 - INFO - Done, deleted /var/run/sdwdate/success." >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - Done, deleted /var/run/sdwdate/success." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
 
    if command -v whonix_firewall >/dev/null 2>&1 ; then
       ## Whonix firewall timesync-fail-closed mode
-      echo "$(date_cmd) - $0 - INFO - Entering Whonix firewall timesync-fail-closed mode." >> /var/log/sdwdate.log
+      echo "$(date_cmd) - $0 - INFO - Entering Whonix firewall timesync-fail-closed mode." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
       firewall_mode="timesync-fail-closed" whonix_firewall
-      echo "$(date_cmd) - $0 - INFO - Done, entered Whonix firewall timesync-fail-closed mode." >> /var/log/sdwdate.log
+      echo "$(date_cmd) - $0 - INFO - Done, entered Whonix firewall timesync-fail-closed mode." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
    else
-      true "$0 INFO: Whonix firewall not installed, probably running outside of Whonix." >> /var/log/sdwdate.log
+      true "$0 INFO: Whonix firewall not installed, probably running outside of Whonix." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
    fi
 else
-   echo "$(date_cmd) - $0 - INFO - sdwdate was not running, no need to stop it." >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - sdwdate was not running, no need to stop it." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
 fi
 
 if systemctl --no-pager status tor@default >/dev/null ; then
-   echo "$(date_cmd) - $0 - INFO - Creating /var/run/sdwdate/tor_was_running.status..." >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - Creating /var/run/sdwdate/tor_was_running.status..." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
    touch /var/run/sdwdate/tor_was_running.status
-   echo "$(date_cmd) - $0 - INFO - Done, created /var/run/sdwdate/tor_was_running.status." >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - Done, created /var/run/sdwdate/tor_was_running.status." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
 
-   echo "$(date_cmd) - $0 - INFO - Stopping Tor..." >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - Stopping Tor..." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
    systemctl --no-pager stop tor@default
-   echo "$(date_cmd) - $0 - INFO - Done, stopped Tor." >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - Done, stopped Tor." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
 else
-   echo "$(date_cmd) - $0 - INFO - Tor was not running, no need to stop it." >> /var/log/sdwdate.log
+   echo "$(date_cmd) - $0 - INFO - Tor was not running, no need to stop it." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
 fi
