removed tlsdate support (https://github.com/Whonix/Whonix/issues/349) for reasons listed https://www.whonix.org/wiki/Dev/TimeSync#tlsdate

diff --git a/usr/bin/sdwdate b/usr/bin/sdwdate
--- a/usr/bin/sdwdate
+++ b/usr/bin/sdwdate
@@ -13,8 +13,6 @@
 
 ## TODO:
 ## - implement --user
-## - refactoring, having "_curl_" in variable names is not that good, because
-##   support for tlsdate has been added as well
 
 #set -x
 
@@ -78,8 +76,6 @@ $SCRIPTNAME [-aDdlpqTux] [long options...]
         --dispatch_post_three                 exec after run of curl
         --nodonefileonerror                   do not create done file on error
         --noexitonerror                       do not exit on error
-        --time-fetching-method                curl or tlsdate
-        --tlsdate-extra-options               tlsdate extra options
         --echo-unixtime                       echo remote unix time even when using --quiet"
 
 #       -u --user                             userid to run as
@@ -245,14 +241,6 @@ sdwdate_defaults() {
       SDWDATE_SCLOCKADJ_WAIT_MAX="1000000000"
    fi
 
-   if [ "$TIME_FETCHING_METHOD" = "" ]; then
-      TIME_FETCHING_METHOD="curl"
-   fi
-
-   if [ "$TLSDATE_EXTRA_OPTIONS" = "" ]; then
-      TLSDATE_EXTRA_OPTIONS="--http"
-   fi
-
    if [ "$ECHO_UNIX_TIME" = "" ]; then
       ECHO_UNIX_TIME="false"
    fi
@@ -409,7 +397,6 @@ sdwdate_parse_cmd_options() {
            -d | --debug)
                DEBUG=1
                CURL_VERBOSE=""
-               TLSDATE_VERBOSE="--verbose"
                shift
                ;;
            -u | --user)
@@ -597,14 +584,6 @@ sdwdate_parse_cmd_options() {
            -q | --quiet)
                QUIET=1
                shift
-               ;;
-           --time-fetching-method)
-               TIME_FETCHING_METHOD=$2
-               shift 2
-               ;;
-           --tlsdate-extra-options)
-               TLSDATE_EXTRA_OPTIONS=$2
-               shift 2
                ;;
            --echo-unixtime)
                ECHO_UNIX_TIME=true
@@ -845,8 +824,6 @@ sdwdate_sanity_tests() {
    command -v shuf >/dev/null
    command -v /usr/lib/sclockadj >/dev/null
    command -v /sbin/hwclock >/dev/null
-   ## TODO: when jessie becomes stable
-   #command -v tlsdate >/dev/null
 
    test -e "/dev/random"
    bash -n "$BASH_SOURCE"
@@ -936,20 +913,6 @@ if [ "$SCRIPT_WAS_SOURCED" = "false" ]; then
    trap "sdwdate_signal_sigusr1" SIGUSR1
 fi
 
-tlsdate_show_log() {
-   trap "sdwdate_error_handler" ERR
-   local tlsdate_stdout tlsdate_stderr
-   if [ -r "$TEMP_DIR/$SDWDATE_CURRENT_POOL" ]; then
-      tlsdate_stdout="$(timeout --kill-after 5 5 cat "$TEMP_DIR/$SDWDATE_CURRENT_POOL")" || tlsdate_stdout="timeout/cat exit code: $?"
-   fi
-   if [ -r "$TEMP_DIR/$SDWDATE_CURRENT_POOL.stderr" ]; then
-      tlsdate_stderr="$(timeout --kill-after 5 5 cat "$TEMP_DIR/$SDWDATE_CURRENT_POOL.stderr")" || tlsdate_stderr="timeout/cat exit code: $?"
-   fi
-   sdwdate_log "tlsdate exit code: ${sdwdate_curl_exit_code[$SDWDATE_CURRENT_POOL]} | tlsdate took ${SDWDATE_DOWNLOAD_TOOK_TIME[$SDWDATE_CURRENT_POOL]}s"
-   sdwdate_log "tlsdate stdout: $tlsdate_stdout"
-   sdwdate_log "tlsdate stderr: $tlsdate_stderr"
-}
-
 sdwdate_get_time_from_remote() {
    trap "sdwdate_error_handler" ERR
 
@@ -957,29 +920,18 @@ sdwdate_get_time_from_remote() {
    LINK_UNPROCESSED="$1"
    IFS="." read -r first second <<< "$LINK_UNPROCESSED"
 
-   if [ "$TIME_FETCHING_METHOD" = "tlsdate" ]; then
-      if [ "$second" = "onion" ]; then
-         LINK_PROCESSED="$LINK_UNPROCESSED"
-         ## TODO: Error handling, because tlsdate cannot connect to .onion domains.
-      else
-         LINK_PROCESSED="https://$LINK_UNPROCESSED"
-      fi
-   elif [ "$TIME_FETCHING_METHOD" = "curl" ]; then
-      if [ "$second" = "onion" ]; then
-         LINK_PROCESSED="$LINK_UNPROCESSED"
-         CURL_MAYBE_USE_HTTPS=""
-      else
-         LINK_PROCESSED="https://$LINK_UNPROCESSED"
-         CURL_MAYBE_USE_HTTPS="--tlsv1 --proto =https"
-      fi
+   if [ "$second" = "onion" ]; then
+      LINK_PROCESSED="$LINK_UNPROCESSED"
+      CURL_MAYBE_USE_HTTPS=""
+   else
+      LINK_PROCESSED="https://$LINK_UNPROCESSED"
+      CURL_MAYBE_USE_HTTPS="--tlsv1 --proto =https"
    fi
 
    if [ "$PROXY" = "" ]; then
       CURL_PROXY=""
-      TLSDATE_PROXY=""
    else
       CURL_PROXY="--socks5-hostname $PROXY"
-      TLSDATE_PROXY="--proxy socks5://$PROXY"
    fi
 
    local current_time
@@ -1005,59 +957,17 @@ sdwdate_get_time_from_remote() {
    touch "$TEMP_DIR/$SDWDATE_CURRENT_POOL.stderr"
    rm "$TEMP_DIR/$SDWDATE_CURRENT_POOL.stderr"
 
-   if [ "$TIME_FETCHING_METHOD" = "curl" ]; then
-      ## --fail not required, because also 404 would include head, which is all we need
-      $CURL \
-         $CURL_MAYBE_USE_HTTPS \
-         --max-time 180 \
-         --head \
-         $CURL_PROXY \
-         $CURL_VERBOSE \
-         $CURL_USER_AGENT \
-         --output "$TEMP_DIR/$SDWDATE_CURRENT_POOL" \
-         "$LINK_PROCESSED" \
-         &
-   elif [ "$TIME_FETCHING_METHOD" = "tlsdate" ]; then
-      ## - tlsdate does not always timeout:
-      ##   https://github.com/ioerror/tlsdate/issues/149
-      ## - tlsdate defaults to tlsv1 as per tlsdate's man page.
-      ## - Long option --host did not work for some reason. Short option -H
-      ##   however worked fine.
-      ## - tlsdate does not work with -H https://www.torproject.org, but with
-      ##   -H www.torproject.org.
-      ## - Using --showtime=human, because --showtime=raw does not work.
-
-      sdwdate_log "Running: timeout --kill-after 5 180 \
-         tlsdate \
-         $TLSDATE_PROXY \
-         $TLSDATE_VERBOSE \
-         $TLSDATE_EXTRA_OPTIONS \
-         --dont-set-clock \
-         --showtime=human \
-         -H \"$LINK_PROCESSED\" \
-         > \"$TEMP_DIR/$SDWDATE_CURRENT_POOL\" \
-         2> \"$TEMP_DIR/$SDWDATE_CURRENT_POOL.stderr\" \
-         &"
-
-      timeout --kill-after 5 180 \
-         tlsdate \
-            $TLSDATE_PROXY \
-            $TLSDATE_VERBOSE \
-            $TLSDATE_EXTRA_OPTIONS \
-            --dont-set-clock \
-            --showtime=human \
-            -H "$LINK_PROCESSED" \
-            > "$TEMP_DIR/$SDWDATE_CURRENT_POOL" \
-            2> "$TEMP_DIR/$SDWDATE_CURRENT_POOL.stderr" \
-            &
-
-      ## `timeout` returns:
-      ## - 124 if sigterm was sufficient
-      ## - 137 if needed to use kill.
-   else
-      msg="Unknown TIME_FETCHING_METHOD: $TIME_FETCHING_METHOD."
-      error "$msg"
-   fi
+   ## --fail not required, because also 404 would include head, which is all we need
+   $CURL \
+      $CURL_MAYBE_USE_HTTPS \
+      --max-time 180 \
+      --head \
+      $CURL_PROXY \
+      $CURL_VERBOSE \
+      $CURL_USER_AGENT \
+      --output "$TEMP_DIR/$SDWDATE_CURRENT_POOL" \
+      "$LINK_PROCESSED" \
+      &
 
    SDWDATE_CURL_PID[$SDWDATE_CURRENT_POOL]="$!"
 
@@ -1080,30 +990,18 @@ sdwdate_get_time_from_remote() {
    fi
 
    if [ ! "${sdwdate_curl_exit_code[$SDWDATE_CURRENT_POOL]}" = "0" ]; then
-      if [ "$TIME_FETCHING_METHOD" = "curl" ]; then
-         local command_v_exit_code="0"
-         command -v /usr/lib/curl-scripts/curl_exit_codes > /dev/null || { command_v_exit_code="$?" ; true; };
-         if [ "$command_v_exit_code" = "0" ]; then
-            ## If /usr/lib/curl-scripts/curl_exit_codes available, use it.
-            local curl_status_message
-            curl_status_message="$(/usr/lib/curl-scripts/curl_exit_codes "${sdwdate_curl_exit_code[$SDWDATE_CURRENT_POOL]}")" || true
-            sdwdate_log "No file could be downloaded from $LINK_PROCESSED. (took ${SDWDATE_DOWNLOAD_TOOK_TIME[$SDWDATE_CURRENT_POOL]}s) (curl_exit_code: ${sdwdate_curl_exit_code[$SDWDATE_CURRENT_POOL]} | curl_status_message: $curl_status_message)"
-         else
-            ## Fallback if /usr/lib/curl-scripts/curl_exit_codes is not available.
-            sdwdate_log "No file could be downloaded from $LINK_PROCESSED. (took ${SDWDATE_DOWNLOAD_TOOK_TIME[$SDWDATE_CURRENT_POOL]}s) (curl_exit_code: ${sdwdate_curl_exit_code[$SDWDATE_CURRENT_POOL]})"
-         fi
-      elif [ "$TIME_FETCHING_METHOD" = "tlsdate" ]; then
-         sdwdate_log "No time could be obtained from $LINK_PROCESSED. (took ${SDWDATE_DOWNLOAD_TOOK_TIME[$SDWDATE_CURRENT_POOL]}s) (tlsdate exit code: ${sdwdate_curl_exit_code[$SDWDATE_CURRENT_POOL]})"
-         tlsdate_show_log
+      local command_v_exit_code="0"
+      command -v /usr/lib/curl-scripts/curl_exit_codes > /dev/null || { command_v_exit_code="$?" ; true; };
+      if [ "$command_v_exit_code" = "0" ]; then
+         ## If /usr/lib/curl-scripts/curl_exit_codes available, use it.
+         local curl_status_message
+         curl_status_message="$(/usr/lib/curl-scripts/curl_exit_codes "${sdwdate_curl_exit_code[$SDWDATE_CURRENT_POOL]}")" || true
+         sdwdate_log "No file could be downloaded from $LINK_PROCESSED. (took ${SDWDATE_DOWNLOAD_TOOK_TIME[$SDWDATE_CURRENT_POOL]}s) (curl_exit_code: ${sdwdate_curl_exit_code[$SDWDATE_CURRENT_POOL]} | curl_status_message: $curl_status_message)"
       else
-         msg="Unknown TIME_FETCHING_METHOD: $TIME_FETCHING_METHOD."
-         error "$msg"
+         ## Fallback if /usr/lib/curl-scripts/curl_exit_codes is not available.
+         sdwdate_log "No file could be downloaded from $LINK_PROCESSED. (took ${SDWDATE_DOWNLOAD_TOOK_TIME[$SDWDATE_CURRENT_POOL]}s) (curl_exit_code: ${sdwdate_curl_exit_code[$SDWDATE_CURRENT_POOL]})"
       fi
       return 0
-   fi
-
-   if [ "$TIME_FETCHING_METHOD" = "tlsdate" ]; then
-      tlsdate_show_log
    fi
 
    test -f "$TEMP_DIR/$SDWDATE_CURRENT_POOL"
@@ -1126,21 +1024,6 @@ sdwdate_parse_date() {
    SDWDATE_PARSE_SUCCESS="false"
 
    test -f "$TEMP_DIR/$SDWDATE_CURRENT_POOL"
-
-   if [ "$TIME_FETCHING_METHOD" = "tlsdate" ]; then
-      ## Parsing not required. tlsdate already did that.
-      local timeout_or_cat_exit_code
-      timeout_or_cat_exit_code="0"
-      WEB_DATE_FROM_TOOL="$(timeout --kill-after 5 5 cat "$TEMP_DIR/$SDWDATE_CURRENT_POOL")" || { timeout_or_cat_exit_code="$?" ; true; };
-      if [ "$timeout_or_cat_exit_code" = "0" ]; then
-         SDWDATE_PARSE_SUCCESS="0"
-         return 0
-      else
-         SDWDATE_PARSE_SUCCESS="false"
-         sdwdate_log "Could not read tlsdate time from file. (WEB_DATE_FROM_TOOL: $WEB_DATE_FROM_TOOL | timeout_or_cat_exit_code: $timeout_or_cat_exit_code)"
-         return 0
-      fi
-   fi
 
    local i
    i="0"
