alternative time fetching method using tlsdate as alternative to curl

diff --git a/usr/bin/sdwdate b/usr/bin/sdwdate
--- a/usr/bin/sdwdate
+++ b/usr/bin/sdwdate
@@ -60,7 +60,9 @@ $SCRIPTNAME [-aDdlpqTux] [long options...]
         --dispatch_pre_three                  exec before first run of curl
         --dispatch_post_three                 exec after run of curl
         --nodonefileonerror
-        --noexitonerror"
+        --noexitonerror
+        --time-fetching-method                curl or tlsdate
+        --tlsdate-extra-options               tlsdate extra options"
 
 #       -u --user                             userid to run as
 }
@@ -217,6 +219,14 @@ sdwdate_defaults() {
       SDWDATE_SCLOCKADJ_WAIT_MAX="1000000000"
    fi
 
+   if [ "$TIME_FETCHING_METHOD" = "" ]; then
+      TIME_FETCHING_METHOD="curl"
+   fi
+
+   if [ "$TLSDATE_EXTRA_OPTIONS" = "" ]; then
+      TLSDATE_EXTRA_OPTIONS=""
+   fi
+
    if [ "${SDWDATE_CURL_DISPATCH_PRE[SDWDATE_POOL_ONE]}" = "" ]; then
       declare -A -g SDWDATE_CURL_DISPATCH_PRE
       SDWDATE_CURL_DISPATCH_PRE[SDWDATE_POOL_ONE]="true"
@@ -369,6 +379,7 @@ sdwdate_parse_cmd_options() {
            -d | --debug)
                DEBUG=1
                CURL_VERBOSE=""
+               TLSDATE_VERBOSE="--verbose"
                shift
                ;;
            -u | --user)
@@ -549,6 +560,14 @@ sdwdate_parse_cmd_options() {
                QUIET=1
                shift
                ;;
+           --time-fetching-method)
+               TIME_FETCHING_METHOD=$2
+               shift 2
+               ;;
+           --tlsdate-extra-options)
+               TLSDATE_EXTRA_OPTIONS=$2
+               shift 2
+               ;;
            --)
                shift
                break
@@ -615,6 +634,8 @@ sdwdate_preparation() {
       who_ami="$(whoami)"
    fi
    sdwdate_log "$FUNCNAME: who_ami is set to $who_ami."
+
+   sdwdate_log "$FUNCNAME: TIME_FETCHING_METHOD is set to $TIME_FETCHING_METHOD."
 }
 
 sdwdate_echo() {
@@ -765,6 +786,9 @@ sdwdate_sanity_tests() {
    command -v shuf >/dev/null
    command -v /usr/lib/sclockadj >/dev/null
    command -v /sbin/hwclock >/dev/null
+   ## TODO: when jessie becomes stable
+   #command -v tlsdate >/dev/null
+
    test -e "/dev/random"
    bash -n "$BASH_SOURCE"
 }
@@ -847,15 +871,32 @@ sdwdate_signal_sigusr1() {
 
 trap "sdwdate_signal_sigusr1" SIGUSR1
 
+tlsdate_show_log() {
+   trap "sdwdate_error_handler" ERR
+   local tlsdate_stdout tlsdate_stderr
+   if [ -r "$TEMP_DIR/$SDWDATE_CURRENT_POOL" ]; then
+      tlsdate_stdout="$(timeout --kill-after 5 5 cat "$TEMP_DIR/$SDWDATE_CURRENT_POOL")" || tlsdate_stdout="timeout/cat exit code: $?"
+   fi
+   if [ -r "$TEMP_DIR/$SDWDATE_CURRENT_POOL.stderr" ]; then
+      tlsdate_stderr="$(timeout --kill-after 5 5 cat "$TEMP_DIR/$SDWDATE_CURRENT_POOL.stderr")" || tlsdate_stderr="timeout/cat exit code: $?"
+   fi
+   sdwdate_log "tlsdate exit code: ${sdwdate_curl_exit_code[$SDWDATE_CURRENT_POOL]}"
+   sdwdate_log "tlsdate stdout: $tlsdate_stdout"
+   sdwdate_log "tlsdate stderr: $tlsdate_stderr"
+}
+
 sdwdate_download() {
    trap "sdwdate_error_handler" ERR
 
    LINK="https://$1"
+   LINK_WITHOUT_HTTPS="$1"
 
    if [ "$PROXY" = "" ]; then
       CURL_PROXY=""
+      TLSDATE_PROXY=""
    else
       CURL_PROXY="--socks5-hostname $PROXY"
+      TLSDATE_PROXY="--proxy socks5://$PROXY"
    fi
 
    sdwdate_log "getUrlDateDiff: "$LINK""
@@ -876,19 +917,59 @@ sdwdate_download() {
    ## Sanity test.
    touch "$TEMP_DIR/$SDWDATE_CURRENT_POOL"
    rm "$TEMP_DIR/$SDWDATE_CURRENT_POOL"
+   touch "$TEMP_DIR/$SDWDATE_CURRENT_POOL.stderr"
+   rm "$TEMP_DIR/$SDWDATE_CURRENT_POOL.stderr"
 
-   ## --fail not required, because also 404 would include head, which is all we need
-   $CURL \
-      --tlsv1 \
-      --proto =https \
-      --max-time 180 \
-      --head \
-      $CURL_PROXY \
-      $CURL_VERBOSE \
-      $CURL_USER_AGENT \
-      --output "$TEMP_DIR/$SDWDATE_CURRENT_POOL" \
-      "$LINK" \
-      &
+   if [ "$TIME_FETCHING_METHOD" = "curl" ]; then
+      ## --fail not required, because also 404 would include head, which is all we need
+      $CURL \
+         --tlsv1 \
+         --proto =https \
+         --max-time 180 \
+         --head \
+         $CURL_PROXY \
+         $CURL_VERBOSE \
+         $CURL_USER_AGENT \
+         --output "$TEMP_DIR/$SDWDATE_CURRENT_POOL" \
+         "$LINK" \
+         &
+   elif [ "$TIME_FETCHING_METHOD" = "tlsdate" ]; then
+      ## TODO:
+      ## - does tlsdate handle timeouts or run forever?
+      ##   https://github.com/ioerror/tlsdate/issues/148
+
+      ## - tlsdate defaults to tlsv1 as per tlsdate's man page.
+      ## - Long option --host did not work for some reason. Short option -H
+      ##   however worked fine.
+      ## - tlsdate does not work with -H https://www.torproject.org, but with
+      ##   -H www.torproject.org.
+      ## - Using --showtime=human, because --showtime=raw does not work.
+
+      sdwdate_log "Running: tlsdate \
+         $TLSDATE_PROXY \
+         $TLSDATE_VERBOSE \
+         $TLSDATE_EXTRA_OPTIONS \
+         --dont-set-clock \
+         --showtime=human \
+         -H \"$LINK_WITHOUT_HTTPS\" \
+         > \"$TEMP_DIR/$SDWDATE_CURRENT_POOL\" \
+         2> \"$TEMP_DIR/$SDWDATE_CURRENT_POOL.stderr\" \
+         &"
+
+      tlsdate \
+         $TLSDATE_PROXY \
+         $TLSDATE_VERBOSE \
+         $TLSDATE_EXTRA_OPTIONS \
+         --dont-set-clock \
+         --showtime=human \
+         -H "$LINK_WITHOUT_HTTPS" \
+         > "$TEMP_DIR/$SDWDATE_CURRENT_POOL" \
+         2> "$TEMP_DIR/$SDWDATE_CURRENT_POOL.stderr" \
+         &
+   else
+      msg="Unknown TIME_FETCHING_METHOD: $TIME_FETCHING_METHOD."
+      error "$msg"
+   fi
 
    SDWDATE_CURL_PID[$SDWDATE_CURRENT_POOL]="$!"
 
@@ -905,18 +986,30 @@ sdwdate_download() {
    SDWDATE_DOWNLOAD_TOOK_TIME[$SDWDATE_CURRENT_POOL]="$(( $TIME_END - $TIME_START ))"
 
    if [ ! "${sdwdate_curl_exit_code[$SDWDATE_CURRENT_POOL]}" = "0" ]; then
-      local command_v_exit_code="0"
-      command -v /usr/lib/curl-scripts/curl_exit_codes > /dev/null || { command_v_exit_code="$?" ; true; };
-      if [ "$command_v_exit_code" = "0" ]; then
-         ## If /usr/lib/curl-scripts/curl_exit_codes available, use it.
-         local curl_status_message
-         curl_status_message="$(/usr/lib/curl-scripts/curl_exit_codes "${sdwdate_curl_exit_code[$SDWDATE_CURRENT_POOL]}")" || true
-         sdwdate_log "No file could be downloaded from $LINK. (curl_exit_code: ${sdwdate_curl_exit_code[$SDWDATE_CURRENT_POOL]} | curl_status_message: $curl_status_message)"
+      if [ "$TIME_FETCHING_METHOD" = "curl" ]; then
+         local command_v_exit_code="0"
+         command -v /usr/lib/curl-scripts/curl_exit_codes > /dev/null || { command_v_exit_code="$?" ; true; };
+         if [ "$command_v_exit_code" = "0" ]; then
+            ## If /usr/lib/curl-scripts/curl_exit_codes available, use it.
+            local curl_status_message
+            curl_status_message="$(/usr/lib/curl-scripts/curl_exit_codes "${sdwdate_curl_exit_code[$SDWDATE_CURRENT_POOL]}")" || true
+            sdwdate_log "No file could be downloaded from $LINK. (curl_exit_code: ${sdwdate_curl_exit_code[$SDWDATE_CURRENT_POOL]} | curl_status_message: $curl_status_message)"
+         else
+            ## Fallback if /usr/lib/curl-scripts/curl_exit_codes is not available.
+            sdwdate_log "No file could be downloaded from $LINK. (curl_exit_code: ${sdwdate_curl_exit_code[$SDWDATE_CURRENT_POOL]})"
+         fi
+      elif [ "$TIME_FETCHING_METHOD" = "tlsdate" ]; then
+         sdwdate_log "No time could be obtained from $LINK. (tlsdate exit code: ${sdwdate_curl_exit_code[$SDWDATE_CURRENT_POOL]})"
+         tlsdate_show_log
       else
-         ## Fallback if /usr/lib/curl-scripts/curl_exit_codes is not available.
-         sdwdate_log "No file could be downloaded from $LINK. (curl_exit_code: ${sdwdate_curl_exit_code[$SDWDATE_CURRENT_POOL]})"
+         msg="Unknown TIME_FETCHING_METHOD: $TIME_FETCHING_METHOD."
+         error "$msg"
       fi
       return 0
+   fi
+
+   if [ "$TIME_FETCHING_METHOD" = "tlsdate" ]; then
+      tlsdate_show_log
    fi
 
    test -f "$TEMP_DIR/$SDWDATE_CURRENT_POOL"
@@ -938,6 +1031,13 @@ sdwdate_parse_date() {
    SDWDATE_PARSE_SUCCESS="1"
 
    test -f "$TEMP_DIR/$SDWDATE_CURRENT_POOL"
+
+   if [ "$TIME_FETCHING_METHOD" = "tlsdate" ]; then
+      ## Parsing not required. tlsdate already did that.
+      WEB_DATE_FROM_TOOL="$(timeout --kill-after 5 5 cat "$TEMP_DIR/$SDWDATE_CURRENT_POOL")" || WEB_DATE_FROM_TOOL="timeout/cat exit code: $?"
+      SDWDATE_PARSE_SUCCESS="0"
+      return 0
+   fi
 
    local i
    i="0"
@@ -971,7 +1071,7 @@ sdwdate_parse_date() {
          fi
          true "Reply from $LINK for the \"Date\" field. Line length: $LINE_LENGTH"
 
-         WEB_DATE_GMT="${LINE#*:}"
+         WEB_DATE_FROM_TOOL="${LINE#*:}"
          SDWDATE_PARSE_SUCCESS="0"
          break
       fi
@@ -983,11 +1083,11 @@ sdwdate_convert_to_unixtime() {
 
    SDWDATE_CONVERT_SUCCESS="0"
 
-   WEB_DATE_UNIXTIME="$(date --date="$WEB_DATE_GMT" +"%s")" || { SDWDATE_CONVERT_SUCCESS="$?" ; true; };
+   WEB_DATE_UNIXTIME="$(date --date="$WEB_DATE_FROM_TOOL" +"%s")" || { SDWDATE_CONVERT_SUCCESS="$?" ; true; };
 
    if [ ! "$SDWDATE_CONVERT_SUCCESS" = "0" ]; then
       sdwdate_log "Bogus reply from $LINK. Could not convert to unixtime. \
-\`date\` failed with exit code: $SDWDATE_CONVERT_SUCCESS. date stdout: $WEB_DATE_UNIXTIME"
+\`date\` failed with exit code: $SDWDATE_CONVERT_SUCCESS. WEB_DATE_FROM_TOOL: $WEB_DATE_FROM_TOOL | date stdout: $WEB_DATE_UNIXTIME"
       return 0
    fi
 
