sanity test

diff --git a/usr/bin/sdwdate b/usr/bin/sdwdate
--- a/usr/bin/sdwdate
+++ b/usr/bin/sdwdate
@@ -323,6 +323,15 @@ sdwdate_read_config_folder() {
             true "skip $i"
             continue
          fi
+         local bash_n_exit_code bash_n_output
+         bash_n_exit_code="0"
+         bash_n_output="$(bash -n "$i" 2>&1)" || { bash_n_exit_code="$?" ; true; };
+         if [ ! "$bash_n_exit_code" = "0" ]; then
+            error "Invalid config file: $i
+bash_n_exit_code: $bash_n_exit_code
+bash_n_output:
+$bash_n_output"
+         fi
          source "$i"
       fi
    done
